### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TheVihara** [NikV2/CombatPlus#11]
**Describe the bug**
Well... I can't make it so the combat system's command blocking excludes the /r command or /msg command  because you probably made it so the command needs to be exactly what it says so its blocked.. Is there any way you can fix that?

**To Reproduce**
In the excludes list add "/msg or /r"

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Server Environment & Version**
Paper 1.16.5

**Additional Information (Optional)**

**Comment by NikV2** [comment]
```java
String command = e.getMessage().replace("/", "");

        if (Config.Setting.COMBATLOG_COMMANDS_EXCLUDED.getStringList().stream().noneMatch(excluded -> excluded.contains(command))) {

            e.setCancelled(true);

            Player player = e.getPlayer();

            player.sendMessage(MsgType.COMBATLOG_COMMAND.getMessage());

            debug(player, "&6Cancelled: &a" + e.getEventName());
        }```
        
        This is the code for it, i could try something different tommorow perhaps.

**Comment by NikV2** [comment]
Try putting it without the / in the config.yml
