### ISSUE TITLE
[BUG] Rename golden apples lets you bypass the cooldown

### ISSUE THREAD

**Issue by Johandrex** [NikV2/CombatPlus#18]
**Describe the bug**
You can rename golden apples in anvils or with /itemrename to bypass the cooldown

**To Reproduce**
1. Rename golden apple
2. The players can now continue eating golden apples without the cooldown hindering them.

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Server Environment & Version**
Previous version: git-Paper-131 (MC: 1.19.2)

**Comment by Johandrex** [comment]
https://github.com/NikV2/CombatPlus/blob/6697c53f612e7cb405a32a3be7978f49d51dfbd3/src/main/java/me/nik/combatplus/modules/impl/EnchantedGoldenAppleCooldown.java

Line 76 -                 || !e.getItem().isSimilar(MiscUtils.ENCHANTED_GOLDEN_APPLE)

halp

**Comment by Lotnest** [comment]
Recommended change that fixes the problem:
`|| !event.getItem().getType().name().contains("GOLDEN_APPLE")`
