### ISSUE TITLE
[BUG] Attack Damage Values

### ISSUE THREAD

**Issue by DerVillion** [NikV2/CombatPlus#20]
**Describe the bug**
When custom Tool Damage is enabled it changes the "green text" on weapons. Changing the default values in the config for new ones, will not change the actual damage or "green text value"

**To Reproduce**
We are on 1.17 - explained above, maybe discuss this on Discord?

**Does the issue still persist on the default config?**
No

**Is the plugin up to date?**
Yes

**Server Environment & Version**
Paper 1.17.1

**Additional Information (Optional)**
![image](https://user-images.githubusercontent.com/95658352/210188055-28ea0ad8-a62f-4570-8a53-d49b856040e5.png)

**Comment by NikV2** [comment]
Not a bug, its intended to work this way.
