### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AwakenR** [NikV2/CombatPlus#23]
**Describe the bug**
A clear and concise description of what the bug is. so i was testing out the pearls cooldown but i cant use a pearl while in combat and i wanna know how fix this bc it wont let me

**To Reproduce**
Steps to reproduce the behavior. throw pearl while in combat

**Does the issue still persist on the default config?**
Yes/No   yes

**Is the plugin up to date?**
Yes/No  yes

**Server Environment & Version**
Your server software (ie Paper 1.12.2)  1.17.1

**Additional Information (Optional)**

**Comment by NikV2** [comment]
Not a bug, its a configuration option u can disable it.
