### ISSUE TITLE
Hello, I have a problem with your plugin, Combat Plus. Sometimes when someone is in combat, they get kicked to the lobby of my network, and when they come back, they are immortal.[BUG]

### ISSUE THREAD

**Issue by DesmodusNetwork** [NikV2/CombatPlus#27]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Does the issue still persist on the default config?**
Yes/No

**Is the plugin up to date?**
Yes/No

**Server Environment & Version**
Your server software (ie Paper 1.12.2)

**Additional Information (Optional)**

**Comment by NikV2** [comment]
Please follow the issue template, i didnt get any information - videos - screenshots - examples - details on how to reproduce.
