### ISSUE TITLE
1.8 Notch Not Working [BUG]

### ISSUE THREAD

**Issue by srrawr11** [NikV2/CombatPlus#28]
Hi, I would like to report that when you eat the notch it doesn't work like the 1.8 ones.
When I eat one it shows the 1.9+ system, even I have activated the section:
  **# Should we modify the player's regeneration?
  enabled: true**

This is how I configurated the yml.
https://pastebin.com/6f0x9hWa

Information:
- Paper 1.16.5
- Java
- Pugin version: 1.6.7

Thanks.

**Comment by NikV2** [comment]
Not a bug, combatplus does not do anything with gapple's regeneration effects.

The option you mentioned is under the custom_player_regen category, which affects the regeneration when the player's hunger is full.

**Comment by srrawr11** [comment]
Ahh okey, so here are one my suggestion.. will be nice if you put old system notchs.

Thanks for your time and your plugin! :)
