### ISSUE TITLE
CombatPlus error

### ISSUE THREAD

**Issue by Flickzbtw4331** [NikV2/CombatPlus#3]
Please check the attachment given below
https://paste.gg/p/anonymous/683244c4462b48269e4f1cd677847196

**Comment by Izibane** [comment]
It doesn't support 1.12x and below 
![image](https://user-images.githubusercontent.com/77923336/116887402-cc7f8080-ac19-11eb-9a2e-347d4962616e.png)

**Comment by NikV2** [comment]
Thank u^^
