### ISSUE TITLE
KingdomsX Plugin Integration

### ISSUE THREAD

**Issue by rohanrhu-smh** [NikV2/CombatPlus#4]
Good Morning

I want to request that the KingdomsX Plugin : https://www.spigotmc.org/resources/kingdomsx.77670/ Be integrated with CombatPlus, This plugin is similar to factions and towny, It says premium on the page but that is only a donation, and the API and the jar download link is on their discord and their github, what i want is, when a player gets in combat with combatplus, they shouldn't be allowed going inside any other claims in KingdomsX.

**Comment by Izibane** [comment]
config issue

**Comment by rohanrhu-smh** [comment]
> config issue

what do you mean by that
