### ISSUE TITLE
[BUG] GAPPLES

### ISSUE THREAD

**Issue by srrawr11** [NikV2/CombatPlus#8]
Using the plugin on Paper 1.16.5.
Latest version of the plugin on spigot.
Edifition Java

Hi mate I want to show you that the gapples are not the same as 1.8 system..
The notch from 1.8 gives you this enchantments
https://i.imgur.com/lTPJF2N.png

and these gives the plugin
https://i.imgur.com/WAHjZxl.png

**Comment by srrawr11** [comment]
Sorry mate but when do you think will be fixed this bug?
Thanks.

**Comment by NikV2** [comment]
Not a bug, CombatPlus doesn't do that
