### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 05ARG** [NikV2/CombatPlus#9]
[16:20:13 ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'reader', line 13, column 3:
      CombatPlus_COMMENT_10: ' Would y ...
      ^
expected <block end>, but found '<scalar>'
 in 'reader', line 18, column 5:
        when an Event gets triggered? (D ...

1.18 paper spigot

**Comment by PhoenixHaven** [comment]
Not only is 1.18 not supported but the problem is legit laid out for you
